##########################################################
# THIS DOCKER COMPOSE ALL BE NEEDED ON LOCAL ENVIRONMENT #
#     CHOOSE ONE OF KAFKA MICROSERVICE / KAFKA MEDEA     #
#                AND COMMENT ONE OF IT                   #
##########################################################

version: '3.8'

networks:
  sinbad-net:
    driver: bridge
    name: sinbad-net

services:
  ###################
  # KAFKA FOR MEDEA #
  ###################
  zookeeper-medea:
    image: "bitnami/zookeeper:3"
    ports:
      - "22181:22181"
      - "22888:22888"
      - "23888:23888"
    environment:
      ZOO_SERVER_ID: 1
      ZOO_TICK_TIME: 2000
      ZOO_PORT_NUMBER: 22181
      ZOO_SERVERS: 0.0.0.0:22888:23888
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - "zookeeper_data:/bitnami"
    networks:
      - sinbad-net

  kafka-medea:
    image: "bitnami/kafka:2"
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:22181
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      # KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://10.0.20.30:9092,EXTERNAL://10.0.20.30:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - "kafka_data:/bitnami"
    restart: on-failure  
    depends_on:
      - zookeeper-medea
    networks:
      - sinbad-net
  
  kafka-ui-medea:
    image: sheepkiller/kafka-manager
    depends_on:
      - zookeeper-medea
    environment:
      ZK_HOSTS: zookeeper:22181
    ports:
      - "9000:9000"
    networks:
      - sinbad-net
  #######################
  # END KAFKA FOR MEDEA #
  #######################

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local